### ISSUE TITLE
Create Advanced Tutorial

### ISSUE THREAD

**Issue by jcubic** [jcubic/jquery.terminal#655]
### I have idea for a new feature for jQuery Terminal

Writing tutorial with section about advanced topics of jQuery Terminal.
This will fix lot of issues with documentation.
This should be next step after reading getting started on Wiki.

- [ ] Keymap and details of events (keypress, keydown) #650
- [ ] mobile quircks and responsive terminal #555
  - [ ] Responsive font-szie #628
  - [ ] Reactive text with echo function
- [ ] Multi-word commands #636
- [ ] Formatters
  - [ ] Inherit styles #616
  - [ ] Advanced usage of formatters (including Big Text formatter #612)
  - [ ] Formatters target #588
- [ ] Advanced docs for interpreter and echo #534

**Comment by jcubic** [comment]
The work is on Wiki [Advanced jQuery Terminal Tutorial](https://github.com/jcubic/jquery.terminal/wiki/Advanced-jQuery-Terminal-Tutorial)
